name: Sonnet 3.7

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-smokes:
    uses: ./.github/workflows/test-base-python-smokes.yml
    with:
      llm_model: anthropic/claude-3.7-sonnet
      llm_base_url: https://openrouter.ai/api/v1
      llm_api_key_name: OPENROUTER_API_KEY
    secrets: inherit