name: Sonnet 3.7

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-smokes:
    uses: ./.github/workflows/test-base-python-smokes.yml
    with:
      llm_model: claude-3-7-sonnet
      llm_base_url: https://api.anthropic.com/v1/
      llm_api_key_name: ANTHROPIC_API_KEY
    secrets: inherit 